let tl=gsap.timeline()

tl.from("#paw , #j",{
    opacity:0,
    scale:1,
    duration:1,
    delay:0.3,
})

tl.from("#a",{
    opacity:0,
    duration:1,
})



tl.from("#b",{
    opacity:0,
    duration:1,
    
})

tl.from("#c",{
    opacity:0,
    duration:1,
    
})

tl.from("#d",{
    opacity:0,
    duration:1,
    
})

tl.from("#e",{
    opacity:0,
    duration:1,
    
})

tl.from("#f",{
    opacity:0,
    duration:1,
    
})

tl.from("#g",{
    opacity:0,
    duration:1,
    
})

tl.from("#h",{
    opacity:0,
    duration:1,
    
})

tl.from("#i",{
    opacity:0,
    duration:1,
    
})


tl.to("#a",{
    opacity:0,
    duration:1,
})



tl.to("#b",{
    opacity:0,
    duration:1,
    
})

tl.to("#c",{
    opacity:0,
    duration:1,
    
})

tl.to("#d",{
    opacity:0,
    duration:1,
    
})

tl.to("#e",{
    opacity:0,
    duration:1,
    
})

tl.to("#f",{
    opacity:0,
    duration:1,
    
})

tl.to("#g",{
    opacity:0,
    duration:1,
    
})

tl.to("#h",{
    opacity:0,
    duration:1,
    
})

tl.to("#i",{
    opacity:0,
    duration:1,
    
})

tl.to("#j,#paw",{
    x:"50%",
})
tl.to("#j,#paw",{
    color: "blue",
})






